### PR TITLE
Port erubi_benchmark template and data to etanni

### PR DESCRIPTION
**Pull request by noahgibbs**
Etanni is an older, extremely simple template-lang format that basically turns your template into an "eval" with a lot of heredocs. It uses Ruby string-interpolation syntax to return a value, and just leaves it directly in the output.

I've verified that other than whitespace the output of the etanni benchmark is identical to the yjit-bench erubi benchmark.

Some quick trials w/ prerelease Ruby (fc218e5977) w/ 10 warmups, 30 non-warmup iters

No-JIT: 468ms
YJIT: 471ms

Ratio in YJIT: 7.1% (quite low)
The speedup is actually slightly negative.

Looks like the fact that Etanni's code is basically an instance_eval of a Proc is biting us.

Here's the stats report:
~~~
method call exit reasons:
                block_arg      10153 (98.1%)
      iseq_complex_callee        157 ( 1.5%)
    cfunc_ruby_array_varg         26 ( 0.3%)
    optimized_method_call          9 ( 0.1%)
invokesuper exit reasons:
    block         62 (100.0%)
leave exit reasons:
    interp_return      21332 (100.0%)
     se_interrupt          1 ( 0.0%)
getblockparamproxy exit reasons:
    (all relevant counters are zero)
getinstancevariable exit reasons:
    idx_out_of_range          2 (100.0%)
setinstancevariable exit reasons:
    (all relevant counters are zero)
opt_aref exit reasons:
    (all relevant counters are zero)
expandarray exit reasons:
    (all relevant counters are zero)
opt_getinlinecache exit reasons:
    (all relevant counters are zero)
invalidation reasons:
    constant_state_bump          9 (81.8%)
       constant_ic_fill          2 (18.2%)
bindings_allocations:          73
bindings_set:                   0
compiled_iseq_count:          380
compiled_block_count:        1247
invalidation_count:            11
constant_state_bumps:           0
inline_code_size:          129984
outlined_code_size:         96272
num_gc_obj_refs:              934
total_exit_count:        19764060
total_insns_count:      603869553
vm_insns_count:         561211027
yjit_insns_count:        62401254
ratio_in_yjit:               7.1%
avg_len_in_yjit:              2.2
Top-20 most frequent exit ops (100.0% of exits):
             opt_aref_with:   19731928 (99.9%)
                      send:      10153 (0.1%)
               invokeblock:        373 (0.0%)
    opt_send_without_block:        197 (0.0%)
               invokesuper:         62 (0.0%)
                     throw:         10 (0.0%)
       getinstancevariable:          2 (0.0%)
      opt_getconstant_path:          2 (0.0%)
                     leave:          1 (0.0%)
          from_branch_stub:          0 (0.0%)
                       nop:          0 (0.0%)
~~~

### CODE REVIEW

**Review by k0kubun — APPROVED** [review]
We're likely not interested in speeding up innate/etanni, but this makes sense as a test case for `instance_eval` of a proc that is more realistic code than a pure micro-benchmark.

**Comment by eregon** [comment]
I initially misread the logic, it's an `instance_eval { ... }` and not an `instance_eval("...")`.
(I would use `instance_exec` to make it clear there is no "eval" actually :p)

Wouldn't it be better to find a usage of `instance_eval` in actually-used Ruby software? etanni seems very little used (https://rubygems.org/gems/etanni) and so not really representative of what gets used in Ruby code running in production.
OTOH it's really simple so that's nice too.

(Comment before I realized it's `instance_eval { ... }`: If we just want an eval-string-like thing, then this ERB benchmark already does that (1 eval per iteration): https://github.com/ruby/ruby/blob/master/benchmark/app_erb.yml)

**Comment by eregon** [comment]
> as a way to benchmark ERB-style string-builder templating versus Etanni-style interpolated-string templating.

Right, that makes sense. The string interpolation is actually not part of benchmark.rb but directly in the template itself.
Etanni for the `<?r` uses `_out_(an array) << heredoc` but inside these heredoc there is string interpolation.

**Comment by eregon** [comment]
FYI results on my computer (`ruby -Iharness benchmarks/etanni/benchmark.rb`):
* Ruby 3.1.2: 619ms
* Ruby 3.1.2 +YJIT: 634ms
* TruffleRuby Native dev: 332ms

And a quick profile:
```
$ ruby --cpusampler --cpusampler.Delay=2000 -Iharness benchmarks/etanni/benchmark.rb
---------------------------------------------------------------------------------------------------------------------
Sampling Histogram. Recorded 975 samples with period 10ms. Missed 0 samples.
  Self Time: Time spent on the top of the stack.
  Total Time: Time spent somewhere on the stack.
---------------------------------------------------------------------------------------------------------------------
Thread[main,5,main]
 Name                              ||             Total Time    ||              Self Time    || Location             
---------------------------------------------------------------------------------------------------------------------
 String#chomp!                     ||             2540ms  26.1% ||             2540ms  26.1% || resource:/truffleruby/core/string.rb~691-751:20202-21636
 String#<<                         ||             2430ms  24.9% ||             2430ms  24.9% || (core)~1:0
 Array#map                         ||             1780ms  18.3% ||             1780ms  18.3% || (core)~1:0
 Hash#[]                           ||             2090ms  21.4% ||             1530ms  15.7% || (core)~1:0
 String#eql?                       ||              560ms   5.7% ||              560ms   5.7% || (core)~1:0
 Array#<<                          ||              520ms   5.3% ||              520ms   5.3% || (core)~1:0
 ThreadOperations.detect_recursion ||             2770ms  28.4% ||              170ms   1.7% || resource:/truffleruby/core/truffle/thread_operations.rb~69-76:3644-3836
 Truffle::Type.try_convert         ||              110ms   1.1% ||              110ms   1.1% || resource:/truffleruby/core/type.rb~354-362:11623-11839
 block in Array#join               ||             2600ms  26.7% ||               40ms   0.4% || resource:/truffleruby/core/array.rb~641:15420-15520
 Truffle::Type.rb_convert_type     ||               20ms   0.2% ||               20ms   0.2% || resource:/truffleruby/core/type.rb~254-262:8899-9173
 Array#join                        ||             2790ms  28.6% ||               10ms   0.1% || resource:/truffleruby/core/array.rb~637-681:15331-16235
 Array#each                        ||             7220ms  74.1% ||               10ms   0.1% || (core)~1:0
 BasicObject#instance_exec         ||             9740ms  99.9% ||               10ms   0.1% || (core)~1:0
 Integer#times                     ||             9750ms 100.0% ||               10ms   0.1% || resource:/truffleruby/core/integer.rb~143-152:4532-4678
 String#initialize_copy            ||               10ms   0.1% ||               10ms   0.1% || (core)~1:0
 block (2 levels) in <unused>      ||             9730ms  99.8% ||                0ms   0.0% || simple_template.etanni~1:0-78
 Benchmark#realtime                ||             9750ms 100.0% ||                0ms   0.0% || ../../.rubies/truffleruby-dev/lib/mri/benchmark.rb~306-310:10288-10441
 String#+@                         ||               10ms   0.1% ||                0ms   0.0% || resource:/truffleruby/core/string.rb~1221-1223:35226-35264
 Etanni#result                     ||             9740ms  99.9% ||                0ms   0.0% || benchmark.rb~34-36:901-989
 Truffle::Boot.main                ||             9750ms 100.0% ||                0ms   0.0% || (core)~1:0
 block in <main>                   ||             9750ms 100.0% ||                0ms   0.0% || benchmark.rb~50:1249-1268
 <main>                            ||             9750ms 100.0% ||                0ms   0.0% || benchmark.rb~1-55:0-1319
 block in Object#run_benchmark     ||             9750ms 100.0% ||                0ms   0.0% || harness/harness.rb~25:629-667
 Kernel#StringValue                ||               20ms   0.2% ||                0ms   0.0% || resource:/truffleruby/core/kernel.rb~170-172:5865-5947
 block (3 levels) in <unused>      ||             7210ms  73.9% ||                0ms   0.0% || simple_template.etanni~30:908-938
 Object#run_benchmark              ||             9750ms 100.0% ||                0ms   0.0% || harness/harness.rb~19-46:542-1441
 block (2 levels) in <main>        ||             9740ms  99.9% ||                0ms   0.0% || benchmark.rb~51:1270-1283
 String.try_convert                ||              110ms   1.1% ||                0ms   0.0% || resource:/truffleruby/core/string.rb~73-75:3060-3143
 Object#run_etanni                 ||             9740ms  99.9% ||                0ms   0.0% || benchmark.rb~42-44:1081-1131
---------------------------------------------------------------------------------------------------------------------
```
Those chomps seem quite expensive. Interpolation I would think is counted indirectly in `simple_template.etanni` Location's (a Ruby-level profiler is of course not great to measure interpolation). There is some safepoint bias for the sampling. All `String#<<` calls are from inside `Array#join`.

**Comment by maximecb** [comment]
Thanks for putting this together Noah.

I agree that the time in YJIT looks pretty bad on this benchmark. Might be interesting to see how much work it would be to speed it up at some point. Could also be interesting to design our own string interpolation template rendering benchmark that's designed to work well on YJIT, just to see what we can do, and maybe focus directly on the string interpolation part.

The contents of `gem_specs.json` makes it look like this benchmark has several dependencies, which was surprising to me. Why is that? Are they all indirect dependencies?

**Comment by noahgibbs** [comment]
gem_specs.json isn't dependencies for this benchmark. The original source of this template is an HTTP server that displays information about gems and their dependencies, so that's basically sample data that gets rendered into the template.

**Pull request merged**
