### PR TITLE
First version of the Psych benchmark, testing a few simple YAML files

### PR DESCRIPTION
**Pull request by noahgibbs**
On a c5.metal instance I get around 16% YJIT speedup with this:

~~~
yjit_opts=""
ruby_version="ruby 3.1.0dev (2021-06-10T15:20:58Z main 5df67f1316) [x86_64-linux] YJIT is enabled"
git_branch="main"
git_commit="5df67f1316"
-----  -----------  ----------  ---------  ----------  -----------  ------------
bench  interp (ms)  stddev (%)  yjit (ms)  stddev (%)  interp/yjit  yjit 1st itr
psych  242.6        0.1         209.3      0.1         1.16         1.15
-----  -----------  ----------  ---------  ----------  -----------  ------------
~~~

We talked about trying to figure out what YJIT changes might help the performance of this benchmark. Here are --yjit-stats gathered from my Mac:

~~~
***YJIT: Printing runtime counters from yjit.rb***
Number of bindings allocated: 83
Number of locals modified through binding: 0
method call exit reasons:
          ivar_set_method    3962982 (50.2%)
         optimized_method    1973992 (25.0%)
       cfunc_toomany_args    1913991 (24.2%)
      callsite_not_simple      30154 ( 0.4%)
       iseq_only_keywords      14991 ( 0.2%)
      iseq_complex_callee        127 ( 0.0%)
    cfunc_ruby_array_varg         27 ( 0.0%)
leave exit reasons:
      interp_return    3845306 (64.3%)
    se_finish_frame    2132438 (35.7%)
       se_interrupt          6 ( 0.0%)
getinstancevariable exit reasons:
    undef      14999 (100.0%)
setinstancevariable exit reasons:
    (all relevant counters are zero)
opt_aref exit reasons:
    (all relevant counters are zero)
compiled_iseq_count:          217
inline_code_size:          126829
outlined_code_size:        104752
total_exit_count:        14453823
total_insns_count:      482878529
vm_insns_count:         178495183
yjit_insns_count:       318837169
ratio_in_yjit:              63.0%
avg_len_in_yjit:             21.1
top-20 most frequent exit ops (100.0% of exits):
    opt_send_without_block:    7866394 (54.4%)
                     leave:    2132444 (14.8%)
               invokesuper:    2046114 (14.2%)
                   opt_not:    1943992 (13.4%)
                opt_length:     360235 (2.5%)
                      send:      30155 (0.2%)
        opt_getinlinecache:      30036 (0.2%)
       getinstancevariable:      15000 (0.1%)
                     throw:      14998 (0.1%)
~~~

### CODE REVIEW

**Comment by maximecb** [comment]
`vm_opt_not` can be interesting because we already have a partial implementation of it, so then the question is, why are we still exiting this often?

**Comment by noahgibbs** [comment]
I'll look into those. Question: do we prefer more, smaller benchmarks? I think it'd be a fine idea to test YAML dumping. I wasn't sure how much variety should go into a single benchmark, though. Do you have an opinion on how 'big' this benchmark should be in terms of variety of functionality?

**Comment by noahgibbs** [comment]
The current gen_opt_not wants a clear compile-time Qtrue/Qfalse value (using jit_peek_at_stack) or it side-exits. I *think* that means it will side-exit on most Ruby values, including any "truthy" values other than plain old true. A "not" is very, very frequently used with "truthy" or "falsey" values other than literal true/false, especially with nil.

So I think that's what's happening on opt_not. I'll investigate more.

**Comment by noahgibbs** [comment]
With the wild YAML I get a slightly different distribution of side-exit opcodes too (trimmed slightly):

~~~
    opt_send_without_block:  107688780 (52.6%)
                     leave:   29926333 (14.6%)
               invokesuper:   27580114 (13.5%)
                   opt_not:   25262492 (12.3%)
                opt_length:   14215235 (6.9%)
                      send:      40150 (0.0%)
        opt_getinlinecache:      40036 (0.0%)
       getinstancevariable:      20000 (0.0%)
                     throw:      19998 (0.0%)
          opt_regexpmatch2:       5442 (0.0%)
                 putstring:       4991 (0.0%)
~~~

**Pull request merged**
