### PR TITLE
Fix a few things to run Ruby master on Linux

### PR DESCRIPTION
**Pull request by k0kubun**
## Changes

* Remove `.ruby-version`
  * I believe we benchmark Ruby master here, so we shouldn't lock the version to an old one.
* Remove arch-specific Nokogiri installation like `1.13.6-x86_64-linux` and `1.13.6-x86_64-darwin`
  * I think Nokogiri's binary releases support only existing Ruby versions, and `bundle install` seems to crash as long as you have those entries in Gemfile.lock.
  * You should build the extension from source if you want to benchmark Ruby master.

## bundle install failure

<details>
<summary>Click here if you want to read it</summary>

$ bundle -j24
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
--- ERROR REPORT TEMPLATE -------------------------------------------------------
```
NoMethodError: undefined method `version' for #<Bundler::IncompleteSpecification:0x00007efce7b0a6b8 @name="nokogiri", @platform=nil>
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/index.rb:84:in `block in sort_specs'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/index.rb:82:in `each'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/index.rb:82:in `sort_by'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/index.rb:82:in `sort_specs'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/spec_set.rb:159:in `lookup'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/spec_set.rb:184:in `block in tsort_each_child'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/spec_set.rb:182:in `each'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/spec_set.rb:182:in `tsort_each_child'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/vendor/tsort/lib/tsort.rb:415:in `call'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/vendor/tsort/lib/tsort.rb:415:in `each_strongly_connected_component_from'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/vendor/tsort/lib/tsort.rb:349:in `block in each_strongly_connected_component'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/spec_set.rb:168:in `block in tsort_each_node'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/spec_set.rb:168:in `each'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/spec_set.rb:168:in `tsort_each_node'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/vendor/tsort/lib/tsort.rb:347:in `call'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/vendor/tsort/lib/tsort.rb:347:in `each_strongly_connected_component'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/vendor/tsort/lib/tsort.rb:226:in `tsort_each'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/vendor/tsort/lib/tsort.rb:176:in `each'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/vendor/tsort/lib/tsort.rb:176:in `to_a'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/vendor/tsort/lib/tsort.rb:176:in `tsort'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/vendor/tsort/lib/tsort.rb:152:in `tsort'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/spec_set.rb:143:in `sorted'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/spec_set.rb:135:in `each'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/installer.rb:243:in `ensure_specs_are_compatible!'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/installer.rb:83:in `block in run'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/process_lock.rb:12:in `block in lock'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/process_lock.rb:9:in `open'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/process_lock.rb:9:in `lock'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/installer.rb:71:in `run'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/installer.rb:23:in `install'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/cli/install.rb:62:in `run'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/cli.rb:257:in `block in install'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/settings.rb:132:in `temporary'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/cli.rb:256:in `install'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/cli.rb:31:in `dispatch'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/cli.rb:25:in `start'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/gems/3.2.0+2/gems/bundler-2.4.0.dev/libexec/bundle:48:in `block in <top (required)>'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/3.2.0+2/bundler/friendly_errors.rb:120:in `with_friendly_errors'
  /home/k0kubun/.rbenv/versions/yjit/lib/ruby/gems/3.2.0+2/gems/bundler-2.4.0.dev/libexec/bundle:36:in `<top (required)>'
  /home/k0kubun/.rbenv/versions/yjit/bin/bundle:25:in `load'
  /home/k0kubun/.rbenv/versions/yjit/bin/bundle:25:in `<main>'
```
## Environment
```
Bundler       2.4.0.dev
  Platforms   ruby, x86_64-linux
Ruby          3.2.0p-1 (2022-08-19 revision 5d0b256f686d943c7648086e782ff4785ffb75dc) [x86_64-linux]
  Full Path   /home/k0kubun/.rbenv/versions/yjit/bin/ruby
  Config Dir  /home/k0kubun/.rbenv/versions/yjit/etc
RubyGems      3.4.0.dev
  Gem Home    /home/k0kubun/.rbenv/versions/yjit/lib/ruby/gems/3.2.0+2
  Gem Path    /home/k0kubun/.local/share/gem/ruby/3.2.0+2:/home/k0kubun/.rbenv/versions/yjit/lib/ruby/gems/3.2.0+2
  User Home   /home/k0kubun
  User Path   /home/k0kubun/.local/share/gem/ruby/3.2.0+2
  Bin Dir     /home/k0kubun/.rbenv/versions/yjit/bin
OpenSSL
  Compiled    OpenSSL 3.0.2 15 Mar 2022
  Loaded      OpenSSL 3.0.2 15 Mar 2022
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools
  Git         2.34.1
  RVM         not installed
  rbenv       rbenv 1.2.0-16-gc4395e5
  chruby      not installed
```
## Bundler Build Metadata
```
Built At          2022-08-18
Git SHA           unknown
Released Version  false
```
## Bundler settings
```
jobs
  Set for your local app (/home/k0kubun/src/github.com/Shopify/yjit-bench/benchmarks/railsbench/.bundle/config): 24
  Set via BUNDLE_JOBS: 16
```
### Gemfile
```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
#ruby '3.0.0'
gem 'stackprof', platforms: :mri
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.6'
# Use sqlite3 as the database for Active Record
gem 'sqlite3', '~> 1.4', platform: :ruby
gem 'activerecord-jdbcsqlite3-adapter', '~> 60.4', platform: :jruby
# Use webrick for the web server since it's easy to install.
# The web server is not used during the benchmark.
gem 'webrick', '~> 1.7.0'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# Needed in the benchmark for json responses
gem 'jbuilder', '~> 2.7'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
# gem 'webpacker', '~> 4.0'
# Benchmark doesn't use Turbolinks
# gem 'turbolinks', '~> 5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'
# Use Active Storage variant
# gem 'image_processing', '~> 1.2'
# Reduces boot times through caching; required in config/boot.rb
#gem 'bootsnap', '>= 1.4.2', require: false
gem 'psych', '~> 3.3.2'
group :development do
  gem 'listen', '~> 3.2'
end
if RUBY_VERSION >= "3.1"
  # net-smtp, net-imap and net-pop were removed from default gems in Ruby 3.1
  gem "net-smtp", "~> 0.2.1", require: false
  gem "net-imap", "~> 0.2.1", require: false
  gem "net-pop", "~> 0.1.1", require: false
  # matrix was removed from default gems in Ruby 3.1, but is used by the `capybara` gem.
  # So we need to add it as a dependency until `capybara` is fixed: https://github.com/teamcapybara/capybara/pull/2468
  #gem "matrix", require: false
end
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```
### Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (6.0.4)
      actionpack (= 6.0.4)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.0.4)
      actionpack (= 6.0.4)
      activejob (= 6.0.4)
      activerecord (= 6.0.4)
      activestorage (= 6.0.4)
      activesupport (= 6.0.4)
      mail (>= 2.7.1)
    actionmailer (6.0.4)
      actionpack (= 6.0.4)
      actionview (= 6.0.4)
      activejob (= 6.0.4)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.0.4)
      actionview (= 6.0.4)
      activesupport (= 6.0.4)
      rack (~> 2.0, >= 2.0.8)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.0.4)
      actionpack (= 6.0.4)
      activerecord (= 6.0.4)
      activestorage (= 6.0.4)
      activesupport (= 6.0.4)
      nokogiri (>= 1.8.5)
    actionview (6.0.4)
      activesupport (= 6.0.4)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (6.0.4)
      activesupport (= 6.0.4)
      globalid (>= 0.3.6)
    activemodel (6.0.4)
      activesupport (= 6.0.4)
    activerecord (6.0.4)
      activemodel (= 6.0.4)
      activesupport (= 6.0.4)
    activerecord-jdbc-adapter (60.4-java)
      activerecord (~> 6.0.0)
    activerecord-jdbcsqlite3-adapter (60.4-java)
      activerecord-jdbc-adapter (= 60.4)
      jdbc-sqlite3 (~> 3.8, < 3.30)
    activestorage (6.0.4)
      actionpack (= 6.0.4)
      activejob (= 6.0.4)
      activerecord (= 6.0.4)
      marcel (~> 1.0.0)
    activesupport (6.0.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
      zeitwerk (~> 2.2, >= 2.2.2)
    builder (3.2.4)
    concurrent-ruby (1.1.9)
    crass (1.0.6)
    erubi (1.10.0)
    ffi (1.15.3)
    ffi (1.15.3-java)
    globalid (0.5.2)
      activesupport (>= 5.0)
    i18n (1.8.10)
      concurrent-ruby (~> 1.0)
    jar-dependencies (0.4.1)
    jbuilder (2.11.2)
      activesupport (>= 5.0.0)
    jdbc-sqlite3 (3.28.0)
    listen (3.7.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    loofah (2.11.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.1)
    method_source (1.0.0)
    mini_mime (1.1.0)
    mini_portile2 (2.8.0)
    minitest (5.14.4)
    nio4r (2.5.7)
    nio4r (2.5.7-java)
    nokogiri (1.13.6)
      mini_portile2 (~> 2.8.0)
      racc (~> 1.4)
    nokogiri (1.13.6-java)
      racc (~> 1.4)
    nokogiri (1.13.6-x86_64-darwin)
      racc (~> 1.4)
    nokogiri (1.13.6-x86_64-linux)
      racc (~> 1.4)
    psych (3.3.2)
    psych (3.3.2-java)
      jar-dependencies (>= 0.1.7)
    racc (1.6.0)
    racc (1.6.0-java)
    rack (2.2.3.1)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (6.0.4)
      actioncable (= 6.0.4)
      actionmailbox (= 6.0.4)
      actionmailer (= 6.0.4)
      actionpack (= 6.0.4)
      actiontext (= 6.0.4)
      actionview (= 6.0.4)
      activejob (= 6.0.4)
      activemodel (= 6.0.4)
      activerecord (= 6.0.4)
      activestorage (= 6.0.4)
      activesupport (= 6.0.4)
      bundler (>= 1.3.0)
      railties (= 6.0.4)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.3.0)
      loofah (~> 2.3)
    railties (6.0.4)
      actionpack (= 6.0.4)
      activesupport (= 6.0.4)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.20.3, < 2.0)
    rake (13.0.6)
    rb-fsevent (0.11.0)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    sass-rails (6.0.0)
      sassc-rails (~> 2.1, >= 2.1.1)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    sprockets (4.0.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.2)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sqlite3 (1.4.2)
    stackprof (0.2.17)
    thor (1.1.0)
    thread_safe (0.3.6)
    thread_safe (0.3.6-java)
    tilt (2.0.10)
    tzinfo (1.2.10)
      thread_safe (~> 0.1)
    tzinfo-data (1.2021.5)
      tzinfo (>= 1.0.0)
    webrick (1.7.0)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-driver (0.7.5-java)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    zeitwerk (2.4.2)
PLATFORMS
  ruby
  universal-java-11
  x86_64-darwin-20
  x86_64-linux
DEPENDENCIES
  activerecord-jdbcsqlite3-adapter (~> 60.4)
  jbuilder (~> 2.7)
  listen (~> 3.2)
  psych (~> 3.3.2)
  rails (~> 6.0.3, >= 6.0.3.6)
  sass-rails (>= 6)
  sqlite3 (~> 1.4)
  stackprof
  tzinfo-data
  webrick (~> 1.7.0)
BUNDLED WITH
   2.3.0.dev
```
--- TEMPLATE END ----------------------------------------------------------------
Unfortunately, an unexpected error occurred, and Bundler cannot continue.
First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=undefined+method+%60version%27+for+%23%3CBundler++IncompleteSpecification+0x00007efce7b0a6b8+%40name%3D%22nokogiri%22%2C+%40platform%3Dnil%3E&type=Issues
If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.

</details>

### CODE REVIEW

**Comment by k0kubun** [comment]
Well, I didn't notice https://github.com/Shopify/yjit-bench/pull/75, but it seems to deal with the same thing.

**Review by noahgibbs — APPROVED** [review]

**Comment by eregon** [comment]
> I believe we benchmark Ruby master here, so we shouldn't lock the version to an old one.

Not only, as it seems very useful that recent Ruby versions should also work for comparison, but agreed these `.ruby-version` are not useful.

**Comment by eregon** [comment]
Was the Bundler bug reported? I think in #75 we established it was clearly a Bundler bug (the output is different here).

**Comment by k0kubun** [comment]
> Was the Bundler bug reported?

Huh, I was about to click "Submit new issue" with the issue template content in this PR's description, but https://github.com/rubygems/rubygems/issues/5849 was filed 23 minutes ago.

**Comment by flavorjones** [comment]
For future reference, I'm pretty sure that the combination of [this fix to bundler](https://github.com/rubygems/rubygems/pull/5784) and adding `ruby` as a bundler platform should resolve the issue noted above wrt precompiled gems being present and not matching Ruby master.

**Pull request merged**
