### PR TITLE
Update nbody to mame's version

### PR DESCRIPTION
**Pull request by jhawthorn**
Slightly faster version via https://twitter.com/mametter/status/1437595050565718022

I'm not sure if we want to update this or not, but as we currently show no improvement on nbody and only jit ~7% it seems like a good time.

### CODE REVIEW

**Comment by maximecb** [comment]
The code is not very different. Definitely doesn't seem like it would be more efficient.

Is this the version typically used to benchmark CRuby and other Ruby JITs?

**Comment by jhawthorn** [comment]
It's new but I assume it would be the version being looked at since it's the fastest on https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/nbody-ruby-3.html

I was mostly interested in this from the tweet

**Comment by maximecb** [comment]
Okay ;)

**Comment by maximecb** [comment]
Looks like with your changes we get 99.9% coverage on it

**Pull request merged**
